### ISSUE TITLE
Error creating New Monitor

### ISSUE THREAD

**Issue by Hughwilkinson** [simnyc/poshdog#2]
I am trying to create a new monitor using this:

$options = @{timeout_h=0; thresholds=1; renotify_interval=0; no_data_timeframe=2}

New-DDMonitor -Type "service check" -Query {"http.can_connect".over("instance:xxxxx.com").last(5).count_by_status()}`
 -Name "test name" -Message "{{url}} on {{host.name}} @notifications@xxxxx.com" -Options $options

but i get this error:
Request to Datadog API backend was NOT successful; It returned this: {"errors":["Thresholds must be of type dictionary."]}

How can we create this monitor and set the threshold levels?

Thanks

**Comment by simnyc** [comment]
Hi @Hughwilkinson , thanks for reporting this one. 

At 1st glance here is what comes to mind. From the API doc:

```
thresholds a dictionary of thresholds by status. Because service checks can have multiple thresholds, we don't define them directly in the query.
Default: {'ok': 1, 'critical': 1, 'warning': 1}
```
So `thresholds` object within`options` must be a hash table. But I'll try to reproduce when I get a minute and will update you.

**Comment by simnyc** [comment]
@Hughwilkinson 

So I think this would solve your issue:

```
$options = @{timeout_h=1; renotify_interval=90; no_data_timeframe=2}
$thresholds=@{'ok'=1; critical='3'; 'warning'=2}
$options.add('thresholds',$thresholds)
PS C:\Users\vagrant> New-DDMonitor -Type "service check" -Query {"http.can_connect".over("instance:xxxxx.com").last(5).count_by_status()}`
>> -Name "test name" -Message "{{url}} on {{host.name}} @notifications@xxxxx.com" -Options $options

id      : 1604818
name    : test name
type    : service check
query   : "http.can_connect".over("instance:xxxxx.com").last(5).count_by_status()
message : {{url}} on {{host.name}} @notifications@xxxxx.com
options : @{notify_audit=False; locked=False; timeout_h=1; silenced=; thresholds=; new_host_delay=300; notify_no_data=False; renotify_interval=90; no_data_timeframe=2}
tags    : {}
created : 2017-02-09T04:30:25.465076+00:00
```

Let me know if this helped.

**Comment by Hughwilkinson** [comment]
that looks like it has worked. Thanks very much.

**Comment by Hughwilkinson** [comment]
another quick question- is it possible to pass avariable into the query string? i was trying this:

-Query {"http.can_connect".over("instance:$instance","region:$region").by("host","instance","url")

but it just created the monitor with instance:$instance rather than the variable itself.

Thanks

**Comment by simnyc** [comment]
@Hughwilkinson Yes you must double the double quotes:

```
PS C:\Users\vagrant> New-DDMonitor -Type 'service check' -Query """my.custom.check"".over(""instance:$instance"").by(""org_id"").last(4).count_by_status()"


id      : 1609634
name    : "my.custom.check".over("instance:i-12345").by("org_id").last(4).count_by_status()
type    : service check
query   : "my.custom.check".over("instance:i-12345").by("org_id").last(4).count_by_status()
message :
options : @{notify_no_data=False; notify_audit=False; locked=False; new_host_delay=300; silenced=}
tags    : {}
created : 2017-02-10T00:02:24.847829+00:00
```

See here: https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.core/about/about_quoting_rules.

Let me know if that helps.

**Comment by Hughwilkinson** [comment]
thanks, wasn't aware of that. Can now go ahead and create 150+ monitors!
